
spring:
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rbac
      initial-size: 5
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    restart:
      enabled: true  #\u8BBE\u7F6E\u5F00\u542F\u70ED\u90E8\u7F72
  freemarker:
    cache: false    #\u9875\u9762\u4E0D\u52A0\u8F7D\u7F13\u5B58\uFF0C\u4FEE\u6539\u5373\u65F6\u751F\u6548

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.by.model

# \u914D\u7F6Epagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count